title: TWX Blog
baseurl: /
permalink: '/:title/'
layout_style: grid
palette: green
header:
  has_nav: true
  logo_img: images/logo.png
  title: TWX Title
footer:
  content: '&copy; All rights reserved.'
  has_social: true
  links:
    - new_window: true
      text: Example
      url: 'http://example.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
